# Generated by Django 4.1.5 on 2023-02-20 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0005_remove_comment_replies_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='discuss_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
